{{- if and .Values.server.enabled .Values.rbac.create (eq .Values.newrelic.scrape_nodes false) .Values.newrelic.namespaces -}}
{{ range $.Values.newrelic.namespaces -}}
---
apiVersion: {{ template "rbac.apiVersion" $ }}
kind: Role
metadata:
  labels:
    {{- include "prometheus.server.labels" $ | nindent 4 }}
  name: {{ template "prometheus.server.fullname" $ }}
  namespace: {{ . }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
{{- end }}
{{- end }}
